# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      # specify the version
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/AppsterdamMilan/hangoutschatbot
    steps:
      - checkout

      # install dep and retrieve dependencies
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure

      # run tests (if any...)
      - run: go test -v ./...

  build:
    machine: true
    steps:
      - checkout

      # build and push docker image
      - run: make docker-build
      - run: make docker-push

workflows:
  version: 2
  on-commit:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
      - build:
          requires:
            - test